name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ACR_NAME: tgpacrkt34yxp4xc3hs
  RESOURCE_GROUP: rg-tgp-prod-northcentralus

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC login if used, or SP login
    
    strategy:
      matrix:
        service:
          - name: tgp.userdashboard
            context: TGP.UserDashboard
            file: TGP.UserDashboard/Dockerfile
            appName: tgp-dashboard-prod
          - name: tgp.microservices.sso
            context: TGP.Microservices.SSO
            file: TGP.Microservices.SSO/Dockerfile
            appName: tgp-sso-prod
          - name: tgp.microservices.devicegateway
            context: TGP.Microservices.DeviceGateway
            file: TGP.Microservices.DeviceGateway/Dockerfile
            appName: tgp-gateway-prod
          - name: tgp.microservices.reporting
            context: TGP.Microservices.Reporting
            file: TGP.Microservices.Reporting/Dockerfile
            appName: tgp-reporting-prod
          - name: tgp.microservices.analysis
            context: TGP.Microservices.Analysis
            file: TGP.Microservices.Analysis/Dockerfile
            appName: tgp-analysis-prod
          - name: tgp.adminportal
            context: TGP.AdminPortal
            file: TGP.AdminPortal/Dockerfile
            appName: tgp-admin-prod
          - name: tgp.microservices.api
            context: TGP.Microservices.Api
            file: TGP.Microservices.Api/Dockerfile
            appName: tgp-api-prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.file }}
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/${{ matrix.service.name }}:latest,${{ env.ACR_NAME }}.azurecr.io/${{ matrix.service.name }}:${{ github.sha }}
          build-args: |
             GH_TOKEN=${{ secrets.GH_PAT }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ env.ACR_NAME }}
          containerAppName: ${{ matrix.service.appName }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/${{ matrix.service.name }}:${{ github.sha }}
